name: tf-pwa-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - ipython
  - pandas
  - tqdm
  - h5py
  - numba
  - git
  - pip:
      - tensorflow>=2.7
      - tensorflow-probability
      - pyyaml
      - graphviz
